
host: localhost


development:
  adapter: postgresql
  encoding: unicode
  database: wilr_development
  pool: 5
  host: localhost


test:
  adapter: postgresql
  encoding: unicode
  database: wilr_test
  pool: 5

production:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: wilr_production
  pool: 5


